apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws::747888353012:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::747888353012:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1I7ASCL8WE9F6
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-29T17:18:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1596"
  uid: cb800bae-e852-41b4-b58e-6aa5ccfe9d69
