apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::922569366551:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::922569366551:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1R5V6GCDHB15J
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-30T21:02:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4380"
  uid: fe9cff7b-9dc7-4f5b-9e73-1389406c5f7a
